name: ocl
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - ca-certificates=2023.08.22
  - certifi=2023.11.17
  - cuda-cudart=11.8.89
  - cuda-cupti=11.8.87
  - cuda-libraries=11.8.0
  - cuda-nvrtc=11.8.89
  - cuda-nvtx=11.8.86
  - cuda-runtime=11.8.0
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - libcublas=11.11.3.6
  - libcufft=10.9.0.58
  - libcufile=1.7.1.12
  - libcurand=10.3.3.129
  - libcusolver=11.4.1.48
  - libcusparse=11.7.5.86
  - matplotlib-inline=0.1.6
  - numpy=1.26.2
  - numpy-base=1.26.2
  - pickleshare=0.7.5
  - pip=23.3.1
  - python=3.10.12
  - python-dateutil=2.8.2
  - pytorch=2.0.1
  - pytorch-cuda=11.8
  - pytorch-mutex=1.0
  - requests=2.31.0
  - scikit-learn=1.3.0
  - setuptools=68.0.0
  - torchaudio=2.0.2
  - torchvision=0.15.2
  - typing_extensions=4.7.1
  - pip:
      - annotated-types==0.6.0
      - async-timeout==4.0.3
      - datasets==2.14.4
      - huggingface-hub==0.20.2
      - matplotlib==3.7.2
      - multiprocess==0.70.15
      - nltk==3.8.1
      - openai==1.8.0
      - pandas==2.0.3
      - pyyaml==6.0.1
      - regex==2023.8.8
      - requests-oauthlib==1.3.1
      - rsa==4.9
      - scipy==1.11.2
      - seaborn==0.12.2
      - sentence-transformers==2.2.2
      - sentencepiece==0.1.99
      - tensorboard==2.15.1
      - tensorboard-data-server==0.7.2
      - tiktoken==0.5.2
      - tokenizers==0.13.3
      - tqdm==4.66.1
      - transformers==4.32.0
